- src/main/java/org/helloworld/gymmate/domain/user/member/service/GymmateUserDetailsService.java
- src/main/java/org/helloworld/gymmate/domain/user/model/GymmateUser.java
- src/main/java/org/helloworld/gymmate/domain/user/service/GymmateUserDetailsService.java
- src/main/java/org/helloworld/gymmate/domain/user/service/GymmateUserService.java
- src/main/java/org/helloworld/gymmate/security/authentication/AuthGymmateUserProvider.java
- src/main/java/org/helloworld/gymmate/security/authentication/GymmateUserDetails.java
- src/main/java/org/helloworld/gymmate/security/authentication/GymmateUserDetailsService.java
- src/main/java/org/helloworld/gymmate/security/oauth2/LoginSuccessHandler.java
refactor(user): GymmateUser (소셜 로그인용 모델) 위치 이동
---
- user
---
- GymmateUser: 소셜 로그인용 모델
- Trainer: 트레이너 엔티티 (DB 테이블과 동일)
- Member: 일반회원 엔티티 (DB 테이블과 동일)
---
---
---
---
- 소셜 로그인 연결
---
- [GYMMATE-54](https://dia19.atlassian.net/browse/GYMMATE-54)
---
[GYMMATE-54]: https://dia19.atlassian.net/browse/GYMMATE-54?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor(user): Move GymmateUser Files

- src/main/java/org/helloworld/gymmate/domain/pt/pt_product/controller/PtProductController.java
- src/main/java/org/helloworld/gymmate/domain/pt/pt_product/service/PtProductService.java
---
- pt
- ptProduct
---
- ptProduct, ptProductImage 관련 전부삭제
- s3에서도 삭제
---
---
---
- 확인해줬으면 하는 부분
---
---
---
> feat(ptProduct) : ptProduct 삭제 및 연관 이미지 삭제

- src/main/java/org/helloworld/gymmate/domain/myself/record/controller/RecordController.java
- src/main/java/org/helloworld/gymmate/domain/myself/record/dto/RecordCreateRequest.java
- src/main/java/org/helloworld/gymmate/domain/myself/record/dto/RecordModifyRequest.java
- src/main/java/org/helloworld/gymmate/domain/myself/record/dto/RecordResponse.java
- src/main/java/org/helloworld/gymmate/domain/myself/record/entity/Record.java
- src/main/java/org/helloworld/gymmate/domain/myself/record/repository/RecordRepository.java
- src/main/java/org/helloworld/gymmate/domain/myself/record/service/RecordService.java
---
- myself
- 운동 일지
---
- RecordController 구현
로그인 부분 구현 완료 후 인증된 member 가져오는 로직 수정 필요
- 운동 일지 생성 구현
RecordService의 createRecord 구현
---
---
---
- .
---
- deleteRecord, modifyRecord, getRecords 구현
- mapper 분리
- 예외처리 로직 추가
---
- [GYMMATE-147](https://dia19.atlassian.net/browse/GYMMATE-147)
---
[GYMMATE-147]: https://dia19.atlassian.net/browse/GYMMATE-147?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(myself): Implement RecordController & CreateRecord

- src/main/java/org/helloworld/gymmate/domain/user/member/controller/MemberController.java
- src/main/java/org/helloworld/gymmate/domain/user/member/dto/MemberRequest.java
- src/main/java/org/helloworld/gymmate/domain/user/member/dto/MemberResponse.java
- src/main/java/org/helloworld/gymmate/domain/user/member/entity/Member.java
- src/main/java/org/helloworld/gymmate/domain/user/member/mapper/MemberMapper.java
- src/main/java/org/helloworld/gymmate/domain/user/member/repository/MemberRepository.java
- src/main/java/org/helloworld/gymmate/domain/user/member/service/MemberService.java
- src/main/java/org/helloworld/gymmate/security/oauth/service/CustomOAuth2UserService.java
- member 회원가입
---
- 회원가입 후 추가정보 등록
- CustomOauth2Service 클래스의 laodUserByUserId에 member용 코드 추가
- member 컨트롤러 : member 추가정보 등록, 추가정보등록여부 확인 , 조회
- memberRequest DTO에서 gender 필드를 String 타입으로 변경 (entity에서는 GenderType사용)
---
- main을 merge 후 실행 문제 발생
---
---
- 멤버 수정, 삭제, 조회
---
---
> feat(member): 회원가입 후 추가정보 등록

- src/main/java/org/helloworld/gymmate/domain/user/member/controller/MemberController.java
- src/main/java/org/helloworld/gymmate/domain/user/member/repository/MemberRepository.java
- src/main/java/org/helloworld/gymmate/domain/user/member/service/MemberService.java
- 멤버 삭제 시 , oauth는 cascade = CascadeType.ALL, orphanRemoval = true로 인해 삭제됨.
- 외래 키 제약조건 때문에 바로 삭제가 안되므로, Trainer 테이블에서 해당 OAuth 관련 데이터가 있는지 확인 및 처리 후 삭제됨...
> feat(member) : member 삭제 로직

- src/main/java/org/helloworld/gymmate/domain/user/trainer/controller/TrainerController.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/dto/TrainerCheckResponse.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/dto/TrainerResponse.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/mapper/TrainerMapper.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/service/TrainerService.java
---
- 도메인
Trainer
---
- 트레이너 마이페이지도 필요 하다고 하셔서 만들었고
- 사장 여부 체크는 마이페이지로 접속할때 화면이 모두 달라서 멤버인지 트레이너인지 체크하고 트레이너라면 사장인지 체크해야한다고 하셨습니다.
---
---
---
- 확인해줬으면 하는 부분
---
- 멤버 쪽에서도 check API를 만들어주셔야 할 것 같습니다!
---
---
> feat(trainer) : 트레이너 마이페이지 조회, 사장 여부 체크 구현

- src/main/java/org/helloworld/gymmate/domain/pt/pt_product/dto/PtProductCreateRequest.java
- src/main/java/org/helloworld/gymmate/domain/pt/pt_product/dto/PtProductModifyRequest.java
- src/main/java/org/helloworld/gymmate/domain/pt/pt_product/dto/PtProductResponse.java
- src/main/java/org/helloworld/gymmate/domain/pt/pt_product/dto/PtProductsResponse.java
- src/main/java/org/helloworld/gymmate/domain/pt/pt_product/entity/PtProduct.java
- src/main/java/org/helloworld/gymmate/domain/pt/pt_product/mapper/PtProductMapper.java
- pt_product
- ptProduct 엔티티 : name필드추가
- Dto: name 필드 추가
- ptProductResponse,ptProductsResonse,ptProductCreateRequest,ptProductModifyRequest
- Mapper : name 변환 추가
- ptProduct 생성,수정,삭제 API 테스트 완료
- [GYMMATE-268](https://dia19.atlassian.net/browse/GYMMATE-268)
[GYMMATE-268]: https://dia19.atlassian.net/browse/GYMMATE-268?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor(pt):name필드 추가

- src/main/java/org/helloworld/gymmate/common/config/SecurityConfig.java
- src/main/java/org/helloworld/gymmate/domain/gym/gymInfo/service/GymService.java
- src/main/java/org/helloworld/gymmate/domain/pt/pt_product/dto/ProductSearchRequest.java
- src/main/java/org/helloworld/gymmate/domain/pt/pt_product/enums/PtProductSearchOption.java
- src/main/java/org/helloworld/gymmate/domain/pt/pt_product/enums/PtProductSortOption.java
- src/main/java/org/helloworld/gymmate/domain/pt/pt_product/repository/PtProductRepository.java
- src/main/java/org/helloworld/gymmate/domain/pt/pt_product/service/PtProductService.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/award/repository/AwardRepository.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/controller/TrainerController.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/dto/TrainerListResponse.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/enums/TrainerSearchOption.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/enums/TrainerSortOption.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/mapper/TrainerMapper.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/repository/TrainerRepository.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/service/TrainerService.java
feat(trainer) : 트레이너 전체 조회 & 검색
---
- trainer
---
- SortOption, SearchOption 트레이너용 / PT상품용 분리
- 트레이너 위치 기반 가까운순 조회 구현
- 트레이너 점수 정렬 & 검색
- 트레이너 최신순 정렬 & 검색
---
---
---
- 확인해줬으면 하는 부분
---
---
---
> feat(trainer) : 트레이너 전체 조회 & 검색

- src/main/java/org/helloworld/gymmate/domain/reservation/controller/ReservationController.java
- src/main/java/org/helloworld/gymmate/domain/reservation/dto/ReservationRequest.java
- src/main/java/org/helloworld/gymmate/domain/reservation/entity/Reservation.java
- src/main/java/org/helloworld/gymmate/domain/reservation/repository/ReservationRepository.java
- src/main/java/org/helloworld/gymmate/domain/reservation/service/ReservationService.java
- reservation
- 컨트롤러 : userId, ReservationRequest,ptProductId 를 서비스에 전달 
- 서비스 : userId, ReservationRequest,ptProductId 로 예약정보, 멤버id,트레이너id를 담은 예약 생성&저장
- ReservationRequest DTO
> feat(reservation): PT예약 등록 로직

- src/main/java/org/helloworld/gymmate/domain/gym/gymInfo/controller/GymController.java
- src/main/java/org/helloworld/gymmate/domain/gym/gymInfo/dto/request/RegisterGymRequest.java
- src/main/java/org/helloworld/gymmate/domain/gym/gymInfo/entity/PartnerGym.java
- src/main/java/org/helloworld/gymmate/domain/gym/gymInfo/service/GymService.java
- src/main/java/org/helloworld/gymmate/domain/gym/gymProduct/dto/GymProductRequest.java
- src/main/java/org/helloworld/gymmate/domain/gym/gymProduct/entity/GymProduct.java
- src/main/java/org/helloworld/gymmate/domain/gym/gymProduct/mapper/GymProductMapper.java
- src/main/java/org/helloworld/gymmate/domain/gym/gymProduct/repository/GymProductRepository.java
- src/main/java/org/helloworld/gymmate/domain/gym/gymProduct/service/GymProductService.java
feat(gymProduct): 헬스장 이용권 
---
- PartnerGym
---
- `GymInfo/dto/request`에 있던 GymproductRequest를 별도의 패키지인 `gymProduct`로 이동했습니다.
- gymProduct는 PartnerGym 생성 이전에 요청(request)으로 전달되므로, 우선 DB에 partnerGym 없이 저장한 후, PartnerGym이 생성된 이후 addGymProduct() 메서드를 통해 연관관계를 설정하는 방식으로 구현했습니다.
(이로써 GymProduct 등록 시 partnerGym의 지연 생성 문제를 회피하면서, 이후 1:N 연관관계를 안전하게 맺을 수 있도록 처리했습니다.)
---
---
- 확인해줬으면 하는 부분
---
---
-  GYMMATE-189
---
> feat(gymProduct): 헬스장 이용권 등록 구현 

- src/main/java/org/helloworld/gymmate/domain/pt/pt_product/service/PtProductService.java
- src/main/java/org/helloworld/gymmate/domain/reservation/controller/ReservationController.java
- src/main/java/org/helloworld/gymmate/domain/reservation/dto/ReservationRequest.java
- src/main/java/org/helloworld/gymmate/domain/reservation/entity/Reservation.java
- src/main/java/org/helloworld/gymmate/domain/reservation/mapper/ReservationMapper.java
- src/main/java/org/helloworld/gymmate/domain/reservation/service/ReservationService.java
- src/test/java/org/helloworld/gymmate/reservation/service/ReservationServiceTest.java
**리팩토링**
- **DTO 유효성 검사** : @ NotBlank , @ min,max 등
- @ Valid 추가 
- **mapper** : toEntity -> ptProduct,ReservationRequest,userId받아서 Reservation객체 생성
- **함수분리** : ptProduceRepository 호출 대신->ptProductService.findProductOrThrow함수 호출
- **httpStatus** : ok -> HttpStatus.CREATED  
**테스트**
- 서비스 테스트 코드 작성 
- '예약 생성', '존재하지 않는 PT 상품으로 예약 시도 시 예외 발생' -> 서비스 테스트 통과 
- [GYMMATE-153](https://dia19.atlassian.net/browse/GYMMATE-153)
[GYMMATE-153]: https://dia19.atlassian.net/browse/GYMMATE-153?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor&test(reservation): 유효성 검사,mapper, 함수분리,httpStatus

- src/main/java/org/helloworld/gymmate/domain/reservation/controller/ReservationController.java
- src/main/java/org/helloworld/gymmate/domain/reservation/dto/ReservationRequest.java
- src/main/java/org/helloworld/gymmate/domain/reservation/dto/ReservationResponse.java
- src/main/java/org/helloworld/gymmate/domain/reservation/mapper/ReservationMapper.java
- src/main/java/org/helloworld/gymmate/domain/reservation/repository/ReservationRepository.java
- src/main/java/org/helloworld/gymmate/domain/reservation/service/ReservationService.java
- src/test/java/org/helloworld/gymmate/reservation/service/ReservationServiceTest.java
feat(reservation) : 수강생의 예약조회 + 트레이너의 예약조회
- reservation
- **수강생의 PT예약 조회** : 로그인한 member id를 통해 예약 내역 확인
- **멤버의 PT예약 조회** : 로그인한 trainer id를 통해 예약 내역 확인
- **레포지터리** : memberId로 예약내역 확인 함수, trainerId로 예약 내역 확인 함수 추가
- [GYMMATE-187](https://dia19.atlassian.net/browse/GYMMATE-187)
[GYMMATE-187]: https://dia19.atlassian.net/browse/GYMMATE-187?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(reservation) : 수강생의 예약조회 + 트레이너의 예약조회

- src/main/java/org/helloworld/gymmate/domain/gym/gymInfo/controller/GymController.java
- src/main/java/org/helloworld/gymmate/domain/gym/gymInfo/dto/request/RegisterGymRequest.java
- src/main/java/org/helloworld/gymmate/domain/gym/gymInfo/dto/request/UpdateGymRequest.java
- src/main/java/org/helloworld/gymmate/domain/gym/gymInfo/dto/response/GymImageResponse.java
- src/main/java/org/helloworld/gymmate/domain/gym/gymInfo/dto/response/GymInfoResponse.java
- src/main/java/org/helloworld/gymmate/domain/gym/gymInfo/dto/response/GymProductResponse.java
- src/main/java/org/helloworld/gymmate/domain/gym/gymInfo/dto/response/PartnerGymDetailResponse.java
- src/main/java/org/helloworld/gymmate/domain/gym/gymInfo/entity/Gym.java
- src/main/java/org/helloworld/gymmate/domain/gym/gymInfo/entity/PartnerGym.java
- src/main/java/org/helloworld/gymmate/domain/gym/gymInfo/mapper/PartnerGymMapper.java
- src/main/java/org/helloworld/gymmate/domain/gym/gymInfo/repository/PartnerGymRepository.java
- src/main/java/org/helloworld/gymmate/domain/gym/gymInfo/service/GymService.java
- src/main/java/org/helloworld/gymmate/domain/gym/gymProduct/entity/GymProduct.java
- src/main/java/org/helloworld/gymmate/domain/gym/gymProduct/mapper/GymProductMapper.java
- src/main/java/org/helloworld/gymmate/domain/gym/gymProduct/repository/GymProductRepository.java
- src/main/java/org/helloworld/gymmate/domain/gym/gymProduct/service/GymProductService.java
- src/main/java/org/helloworld/gymmate/domain/gym/machine/service/MachineService.java
- src/main/java/org/helloworld/gymmate/domain/gym/partnerGym/controller/PartnerGymController.java
- src/main/java/org/helloworld/gymmate/domain/gym/partnerGym/entity/PartnerGym.java
- src/main/java/org/helloworld/gymmate/domain/gym/partnerGym/mapper/PartnerGymMapper.java
- src/main/java/org/helloworld/gymmate/domain/gym/partnerGym/repository/PartnerGymRepository.java
- src/main/java/org/helloworld/gymmate/domain/gym/partnerGym/service/PartnerGymService.java
---
- gym
---
- 같이 병합됨:
#94 
#95 
- gym 도메인 리팩토링 (기본 헬스장과 파트너 헬스장 분리)
- PartnerGymController: 
더이상 파라미터로 `partnerId`를 받지 않습니다
사유: 보안성 개선 (자신의 id 기반으로 조회하도록 해서 자신이 운영하는 헬스장만 접근 가능)
- PartnerGymService: 
`validatePartnerGymOwner`: 기존에 있던 코드를 메소드로 분리함
`getPartnerGymByOwnerId`: 자신의 id를 이용해 운영중인 파트너짐을 가져옵니다
---
---
---
- 많이 바뀌었습니다!!
---
- 후순위: (PartnerGymService) `registerPartnerGym`, `updatePartnerGym` 메소드 중복 로직 리팩토링
- GymProductService 구현
---
- .
---
> refactor(gym): 대규모 - 파트너 헬스장 분리

- src/main/java/org/helloworld/gymmate/domain/gym/gyminfo/controller/GymController.java
- src/main/java/org/helloworld/gymmate/domain/gym/gyminfo/dto/response/TrainerDetailResponse.java
- src/main/java/org/helloworld/gymmate/domain/gym/gyminfo/service/GymService.java
- src/main/java/org/helloworld/gymmate/domain/pt/ptproduct/repository/PtProductRepository.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/mapper/TrainerMapper.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/repository/TrainerRepository.java
- gym
---
- gymId로 소속 트레이너 전체 조회 API 
- 트레이너 정보 + 수상 이력 + PT 상품 포함
- 연관관계 없이 각각 조회 후 Java에서 그룹핑 처리
- TrainerMapper 분리 및 응답 DTO 매핑
---
---
---
- 확인해줬으면 하는 부분
---
---
- GYMMATE-233
---
> feat(gym): 헬스장 소속 트레이너 목록 조회

- src/main/java/org/helloworld/gymmate/domain/gym/gyminfo/dto/response/GymDetailResponse.java
- src/main/java/org/helloworld/gymmate/domain/gym/gyminfo/entity/Gym.java
- src/main/java/org/helloworld/gymmate/domain/gym/gyminfo/mapper/GymMapper.java
- src/main/java/org/helloworld/gymmate/domain/gym/gyminfo/service/GymService.java
- src/main/java/org/helloworld/gymmate/domain/gym/gymproduct/mapper/GymProductMapper.java
- src/main/java/org/helloworld/gymmate/domain/gym/partnergym/repository/PartnerGymRepository.java
- src/main/java/org/helloworld/gymmate/domain/gym/partnergym/service/PartnerGymService.java
---
- 도메인
gym
---
- PartnerGymService에서 updatePartner 호출
- 헬스장 단일 정보 조회시 이용권 정보 추가 
- gymId -> partnerGym -> gymProduct 를 통해 정보를 가져옵니다
---
---
---
- 확인해줬으면 하는 부분
---
---
---
> refactor(gym) : 헬스장 단일 정보 조회시 이용권 정보 추가 

- src/main/java/org/helloworld/gymmate/domain/user/trainer/award/enums/AwardData.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/award/mapper/AwardMapper.java
- src/main/java/org/helloworld/gymmate/infra/domain/trainer/TrainerDummy.java
refactor(trainer):award 더미데이터 생성
- award 예시 12개 -> enum 타입 awardData에 저장
- infra/domain/trainer 폴더에 trainerDummy 파일 생성 
- trainer객체 리스트를 받아서 trainerid와 award정보(name,year,info)를 담은 award 객체를 생성해 리스트에 저장 후 나중에 sql insert문 실행
- sql, jdbcTemplate사용 
- 재현님 코드를 보고 비슷하게 작성하였습니다!
---
---
---
---
> feat(trainer):award 더미데이터 생성

- src/main/java/org/helloworld/gymmate/domain/myself/bigthree/service/BigthreeService.java
- src/main/java/org/helloworld/gymmate/domain/myself/bigthreeaverage/scheduler/BigthreeAverageScheduler.java
- src/main/java/org/helloworld/gymmate/domain/user/member/repository/MemberRepository.java
- src/main/resources/db/migration/V5__insert_missing_bigthree.sql
- src/main/resources/db/migration/V6__reset_null_lifts_and_bigthree.sql
---
- bigthree 
---
- 3대 기록 스케쥴러 개선
프로그램 부팅 시 3대 기록 전체 회원 평균값이 없으면 스케쥴러 실행
- (service) 3대 통계 조회 예외 상황 처리
평균 테이블에 레벨이 없을 경우 0으로 반환
- flyway로 기존 3대 기록 db 데이터 오류 수정
3대 기록이 없는 회원 오늘 날짜로 기록 추가
3대 무게 및 레벨 정보에 오류가 있는 회원 데이터 수정
---
---
---
- 저번에 수정 후 재테스트를 안했어서 (죄송합니다!ㅠㅜㅠ)
이번에는 다 테스트 해봤습니다 혹시 오류나면 또 말씀해주세요
- 오늘 자정 전에 병합해서 pull 하지 않으면 오류가 발생할 수 있습니다
---
- 
---
---
> fix(myself): Improve Bigthree Scheduler & Bigthree Data Correction

- src/main/java/org/helloworld/gymmate/domain/gym/gyminfo/controller/GymController.java
---
- gym
---
- #171 번 PR에 수정 후 병합하지 않고 내용만 가져왔습니다
171번 커밋 내역이 꼬여서요
- #171 번 이후 swagger 약간 수정
- 변수 분리 및 메소드 이름 변경 (로직 변경 없음)
---
---
---
- getGymForTrainer 메소드는 `@PreAuthorize("hasRole('ROLE_TRAINER')")`가 붙어있는데
딱히 트레이너 로그인 상태가 아니어도 작동합니다
로그인을 아예 안하면 안됩니다
swagger에서 테스트 해봤고, 혹시 이유를 아시면 말씀해주세요!
(심각한 사항은 아니라서 우선 병합해도 괜찮을 것 같아요)
---
---
---
> docs(gym): Add Swagger Operation GymController

- src/main/java/org/helloworld/gymmate/domain/pt/reservation/repository/ReservationRepository.java
- src/main/java/org/helloworld/gymmate/domain/user/member/service/MemberService.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/service/TrainerService.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/trainerreview/controller/TrainerReviewController.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/trainerreview/dto/request/TrainerReviewCreateRequest.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/trainerreview/dto/request/TrainerReviewModifyRequest.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/trainerreview/event/TrainerReviewDeleteEvent.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/trainerreview/event/TrainerReviewDeleteEventListener.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/trainerreview/repository/TrainerReviewRepository.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/trainerreview/service/TrainerReviewService.java
---
- 도메인
---
- S3에서 파일을 삭제하는 것도 같은 트랜잭션 내에 이뤄지게 코드를 작성했었는데 이렇게 되면 DB에서 삭제하는건 성공하고 S3에서 삭제는 실패할 경우 롤백이 되기때문에 별도의 트랜잭션에서 이루어지는게 맞는것 같아서 evnet를 적용해 처리하였습니다
- 유효한 예약을 찾을때 현재 시간보다 예약한 시간이 현재 시간보다 이후여야 하므로 그에 맞게 코드를 수정하였습니다
---
---
---
- 리뷰 삭제, 트레이너 탈퇴시 리뷰 삭제 까지 확인하였는데 멤버 회원탈퇴는 아직 테스트 해보지 못했습니다. 문제 있으시면 알려주세요!
- 멤버 회원 탈퇴토 테스트 완료했습니다!
---
트레이너 리뷰 조회
---
---
> feat(trainerreview) : 트레이너 리뷰 삭제 

- src/main/java/org/helloworld/gymmate/domain/gym/partnergym/service/PartnerGymService.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/entity/Trainer.java
- src/main/resources/docs/update_trainer_gymid_by_partnergym.template
---
- 도메인
---
- 파트너짐 등록시 trainer에 gym 업데이트
- 기존 owner 파트너짐 데이터 기반 업데이트 쿼리
---
---
---
- 지금 더미데이터에 trainer 중 is_owner는 1으로 트루인데, partnergym 엔티티가 없는 것들이 있음.
- 있는 trainer는 잘 업데이트 되는데 partnergym 엔티티가 없는 것들은 업데이트가 안됨
---
---
---
> refactor(partnergym) : 파트너짐 등록시 trainer에 gym 업데이트 + 기존 owner 파트너짐 데이터 기반 업데이트 쿼리
