- src/main/java/org/helloworld/gymmate/common/exception/ErrorCode.java
- src/main/java/org/helloworld/gymmate/common/exception/GlobalExceptionHandler.java
- src/main/java/org/helloworld/gymmate/domain/user/GymMateTrainerController.java
- src/main/java/org/helloworld/gymmate/domain/user/dto/OwnerRegisterRequest.java
- src/main/java/org/helloworld/gymmate/domain/user/dto/TrainerRegisterRequest.java
- src/main/java/org/helloworld/gymmate/domain/user/enumerate/GenderType.java
- src/main/java/org/helloworld/gymmate/domain/user/enumerate/SocialProviderType.java
- src/main/java/org/helloworld/gymmate/domain/user/mapper/GymMateTrainerMapper.java
- src/main/java/org/helloworld/gymmate/domain/user/mapper/SocialProviderMapper.java
- src/main/java/org/helloworld/gymmate/domain/user/model/GymmateTrainer.java
- src/main/java/org/helloworld/gymmate/domain/user/model/SocialProvider.java
- src/main/java/org/helloworld/gymmate/domain/user/repository/GymMateTrainerRepository.java
- src/main/java/org/helloworld/gymmate/domain/user/repository/SocialProviderRepository.java
- src/main/java/org/helloworld/gymmate/domain/user/service/GymMateTrainerService.java
- src/main/java/org/helloworld/gymmate/security/authentication/GymMateTrainerDetails.java
먼저 소셜 로그인을 하면 추가 정보를 제외한 기본 정보를 채운 상태로 DB에 저장 됩니다.
그리고 추가 정보 등록 여부 column(additionalInfoCompleted)을 하나 더 설정해서 
그 값을 false로 설정해놓고 추가 정보를 입력 완료를 하면 값을 true로 설정하도록 하였습니다
그리고 저희가 원래 성별 Enum 타입 이름을 Gender 를 쓰리고 했는데 제가 코드를 작성하다보니 java에 이미 Gender.class 라는 클래스가 있어
겹칠것 같아서 GenderType으로 수정하였습니다.
또한 Controller 코드는 인증 파트를 구현하면서 UserDetails 를 만들때 추가하려고 비워놨습니다
> feat(trainer): 추가 정보 등록 구현

- src/main/java/org/helloworld/gymmate/common/exception/ErrorCode.java
- src/main/java/org/helloworld/gymmate/domain/pt/classtime/controller/ClassTimeController.java
- src/main/java/org/helloworld/gymmate/domain/pt/classtime/repository/ClassTimeRepository.java
- src/main/java/org/helloworld/gymmate/domain/pt/classtime/service/ClassTimeService.java
등록되어있는 수강 가능 시간 삭제 기능을 만들었습니다.
추가로 TODO 수정하였고, 기존 에러처리를 까먹었던 등록기능에
에러 처리를 추가했습니다.
> feat(pt) : PT 수강 가능 시간 삭제

- README.md
여전히 PR 템플릿 자동 적용이 되지 않아
PR 템플릿 파일 이름 변경
코드에는 영향이 없어 바로 병합 예정
> docs(readme): Add Swagger&ERD Link /GYMMATE-205

- build.gradle
- src/main/java/org/helloworld/gymmate/common/config/S3Config.java
- src/main/java/org/helloworld/gymmate/common/s3/FileManager.java
- src/main/resources/docs/application.md
feat(common): S3 이미지 파일 업로드 기능
---
- common
---
- S3 의존성 추가
- application.md 수정
- S3 config 추가
- S3 파일 매니저 class 추가
---
.
---
---
- 개인 DM으로 yml 파일 전체 전달했습니다
---
- 잘 되는지 테스트 해봐야합니다
---
- [#GYMMATE-208](https://dia19.atlassian.net/browse/GYMMATE-208)
---
> feat(common): Add S3 FileManager /GYMMATE-208

- src/main/java/org/helloworld/gymmate/domain/pt/classtime/dto/ClasstimesResponse.java
- src/main/java/org/helloworld/gymmate/domain/pt/classtime/mapper/ClasstimeMapper.java
- src/main/java/org/helloworld/gymmate/security/config/SecurityConfig.java
chore(classtime) : 전체조회 DTO 변경
---
- Classtime
---
- 프론트와 상의한 내용, 명세서 반영 후 수정하였습니다.
{
"availableTimes": {
"3": [9, 10, 11],
"4": [15, 16, 17]
}
}
---
---
---
- 확인해줬으면 하는 부분
---
---
---
> chore(classtime) : 전체조회 DTO 변경

- src/main/resources/docs/application.md
config(common): application.md 수정
---
- common
---
S3 config 관련 오류 해결
-> application.md 수정
---
---
---
---
---
---
> config(common): Fix Application.md StaticRegion /GYMMATE-214

- src/main/java/org/helloworld/gymmate/common/exception/ErrorCode.java
중복된 값 요청에서 404 NOT FOUND 에러를 내던 점을 수정했습니다
---
- pt
- classtime
---
---
---
---
- 확인해줬으면 하는 부분
---
---
---
> chore(classtime) : 에러코드 수정

- src/main/java/org/helloworld/gymmate/common/exception/ErrorCode.java
- src/main/java/org/helloworld/gymmate/domain/gym/gym/controller/GymController.java
- src/main/java/org/helloworld/gymmate/domain/gym/gym/dto/GymUpdateRequest.java
- src/main/java/org/helloworld/gymmate/domain/gym/gym/entity/Gym.java
- src/main/java/org/helloworld/gymmate/domain/gym/gym/mapper/GymMapper.java
- src/main/java/org/helloworld/gymmate/domain/gym/gym/service/GymService.java
- gym 도메인 
---
- 기존 이미지에서 삭제할 이미지 선택 후 삭제되는 부분 추가 구현
ex. 기존 이미지 3개 중 2개 지우는 경우
- updateRequest 추가 ( 기존에는 등록 시 썻던 createRequest썼는데 분리하는게 나을것 같아 추가함)
---
---
- commit이 refactor인데 feat으로 작성되었습니다. 이미 push해버려서 commit수정이 복잡할 것 같아 그대로 두었습니다.
(다음에는 커밋 컨벤션 지켜서 작성해두겠습니다)
---
- 일반 헬스장 크롤링
---
- GYMMATE-90
---
> refactor(gym) : 제휴 헬스장 수정 이미지 부분 수정 

- src/main/java/org/helloworld/gymmate/domain/gym/gym/repository/GymRepository.java
- src/main/java/org/helloworld/gymmate/domain/pt/pt_product/controller/PtProductController.java
- src/main/java/org/helloworld/gymmate/domain/pt/pt_product/dto/PtProductResponse.java
- src/main/java/org/helloworld/gymmate/domain/pt/pt_product/mapper/PtProductMapper.java
- src/main/java/org/helloworld/gymmate/domain/pt/pt_product/service/PtProductService.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/award/entity/Award.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/award/repository/AwardRepository.java
feat(ptProduct) : 단일조회 구현
---
- pt
- ptProduct
---
- 단일조회 구현
---
---
다른 데이터가 없어서 테스트를 못해봤습니다.
---
- 확인해줬으면 하는 부분
---
---
---
> feat(ptProduct) : 단일조회 구현

- src/main/java/org/helloworld/gymmate/domain/user/member/entity/Member.java
- src/main/java/org/helloworld/gymmate/domain/user/member/mapper/MemberMapper.java
- src/main/java/org/helloworld/gymmate/domain/user/member/service/MemberService.java
- member
---
- Mapper와 Service 코드에서  socialProvider->oauth
---
- [GYMMATE-71](https://dia19.atlassian.net/browse/GYMMATE-71)
---
[GYMMATE-71]: https://dia19.atlassian.net/browse/GYMMATE-71?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor(member):충돌 해결(socialProvider->oauth)

- src/main/java/org/helloworld/gymmate/domain/myself/record/controller/RecordController.java
- src/main/java/org/helloworld/gymmate/domain/myself/record/dto/RecordCreateRequest.java
- src/main/java/org/helloworld/gymmate/domain/myself/record/dto/RecordModifyRequest.java
- src/main/java/org/helloworld/gymmate/domain/myself/record/dto/RecordResponse.java
- src/main/java/org/helloworld/gymmate/domain/myself/record/entity/Record.java
- src/main/java/org/helloworld/gymmate/domain/myself/record/repository/RecordRepository.java
- src/main/java/org/helloworld/gymmate/domain/myself/record/service/RecordService.java
---
- myself
- record
---
- RecordService의 deleteRecord 구현
- validateRecordOwner: 자신의 운동 기록인지 아닌지 확인하는 메소드
---
---
---
- #30 번 PR과 합쳐져있음
---
- modifyRecord, getRecords 구현
- 에러코드 추가
---
- [GYMMATE-173](https://dia19.atlassian.net/browse/GYMMATE-173)
---
[GYMMATE-173]: https://dia19.atlassian.net/browse/GYMMATE-173?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(myself): Implement DeleteRecord

- src/main/java/org/helloworld/gymmate/domain/user/member/repository/MemberRepository.java
- memberRepository
-memberRepository의 findByOauth(Oauth oauth),findByMemberId
> chore(member):memberRepository 기본적인 함수 추가

- src/main/java/org/helloworld/gymmate/security/handler/LoginSuccessHandler.java
---
- 도메인
---
프론트쪽에서 사용자 추가 정보 입력하는 페이지가 따로 있는것이 아니라 localhost:3000/login 을 그대로 유지한 상태에서 입력을 해야한다고 
하셔서 추가 정보 입력 페이지 redirectUri를 additionalInfoCompleted=false&role=trainer 뒤에 이렇게 파라미터를 붙여 전달드리기로 
했습니다
---
---
---
- 확인해줬으면 하는 부분
---
TrainerController 작업
---
---
> refactor(user): 추가 정보 페이지 URI 수정

- src/main/java/org/helloworld/gymmate/domain/myself/bigthree/controller/BigthreeController.java
- src/main/java/org/helloworld/gymmate/domain/myself/bigthree/dto/BigthreeCreateRequest.java
- src/main/java/org/helloworld/gymmate/domain/myself/bigthree/mapper/BigthreeMapper.java
- src/main/java/org/helloworld/gymmate/domain/myself/bigthree/service/BigthreeService.java
---
- myself
- bigthree
---
- #38 이후 createBigthree 추가
---
---
---
---
- 삭제 & 수정
- 조회
---
- [GYMMATE-149](https://dia19.atlassian.net/browse/GYMMATE-149)
---
[GYMMATE-149]: https://dia19.atlassian.net/browse/GYMMATE-149?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(myself): Implement CreateBigthree

- src/main/java/org/helloworld/gymmate/common/exception/ErrorCode.java
- src/main/java/org/helloworld/gymmate/domain/myself/bigthree/controller/BigthreeController.java
- src/main/java/org/helloworld/gymmate/domain/myself/bigthree/entity/Bigthree.java
- src/main/java/org/helloworld/gymmate/domain/myself/bigthree/mapper/BigthreeMapper.java
- src/main/java/org/helloworld/gymmate/domain/myself/bigthree/repository/BigthreeRepository.java
- src/main/java/org/helloworld/gymmate/domain/myself/bigthree/service/BigthreeService.java
---
- myself
- bigthree 
---
- bigthree에서 공통으로 쓰이는 부분 작성
---
---
---
---
- 생성, 수정, 삭제 로직
- 다양한 조회 로직
---
- [GYMMATE-79](https://dia19.atlassian.net/browse/GYMMATE-79)
---
[GYMMATE-79]: https://dia19.atlassian.net/browse/GYMMATE-79?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(myself): Add Bigthree Package & Implement CreateBigthree

- src/main/java/org/helloworld/gymmate/common/exception/ErrorCode.java
- src/main/java/org/helloworld/gymmate/domain/gym/gym/repository/GymRepository.java
- src/main/java/org/helloworld/gymmate/domain/pt/pt_product/repository/PtProductRepository.java
- src/main/java/org/helloworld/gymmate/domain/pt/pt_product/service/PtProductService.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/business/dto/request/BusinessVerificationRequest.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/business/dto/response/BusinessVerificationResponse.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/business/properties/BusinessProperties.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/business/service/BusinessValidateService.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/controller/TrainerController.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/dto/OwnerRegisterRequest.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/dto/TrainerRegisterRequest.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/mapper/TrainerMapper.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/model/Trainer.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/service/TrainerService.java
- src/main/resources/application-prod.yml
---
- 도메인
---
직원은 헬스장 이름을 요청으로 받고 해당 헬스장을 찾은 후 연결해주는 방식으로 구현했고
사장은 사업자 등록번호 검증 로직을 추가해 구현하였습니다
---
---
---
- 확인해줬으면 하는 부분
---
---
---
> feat(trainer): 트레이너 추가 정보 등록 구현 

- src/main/java/org/helloworld/gymmate/domain/myself/bigthree/controller/BigthreeController.java
- src/main/java/org/helloworld/gymmate/domain/myself/bigthree/service/BigthreeService.java
---
- myself
- bigthree
---
- bigthreeId로 Bigthree를 삭제합니다
---
---
---
---
- 수정
- 조회
---
- [GYMMATE-192](https://dia19.atlassian.net/browse/GYMMATE-192)
---
[GYMMATE-192]: https://dia19.atlassian.net/browse/GYMMATE-192?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(myself): Implement DeleteBigthree

- src/main/java/org/helloworld/gymmate/domain/user/member/dto/MemberRequest.java
- src/main/java/org/helloworld/gymmate/domain/user/member/entity/Member.java
- src/main/java/org/helloworld/gymmate/domain/user/member/mapper/MemberMapper.java
- src/main/java/org/helloworld/gymmate/domain/user/member/service/MemberService.java
- src/main/java/org/helloworld/gymmate/security/handler/LoginSuccessHandler.java
- src/main/java/org/helloworld/gymmate/security/oauth/service/CustomOAuth2UserService.java
- spring security
-  CustomOAuth2UserService의 processOAuth2User메소드의 member 등록 부분
-  member의 추가정보 등록(서비스 코드)
- [GYMMATE-71](https://dia19.atlassian.net/browse/GYMMATE-71)
[GYMMATE-71]: https://dia19.atlassian.net/browse/GYMMATE-71?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor(member): CustomOAuth2UserService의 member 등록 로직

- src/main/java/org/helloworld/gymmate/domain/pt/pt_product/mapper/PtProductMapper.java
refactor(pt) : List.of -> Collections.emptyList()
---
- pt
- ptProduct
---
- 빈 리스트 반환하는것 Collections.emptyList로 변경
---
---
---
- 확인해줬으면 하는 부분
---
---
---
> refactor(pt) : List.of -> Collections.emptyList()

- src/main/java/org/helloworld/gymmate/domain/user/trainer/business/service/BusinessValidateService.java
- src/main/java/org/helloworld/gymmate/infra/domain/gym/SeoulGymWebClientCrawler.java
- src/main/java/org/helloworld/gymmate/security/oauth/service/CustomOAuth2UserService.java
- src/main/java/org/helloworld/gymmate/security/resolver/CustomAuthorizationRequestResolver.java
- src/main/java/org/helloworld/gymmate/security/token/JwtManager.java
refactor(common) : log.info -> log.debug
---
- 여러 도메인이랑 관련이 있는데, common이라고 작성하게되었습니다
---
- log.info -> log.debug
---
---
---
- 확인해줬으면 하는 부분
---
---
---
> refactor(common) : log.info -> log.debug

- src/main/java/org/helloworld/gymmate/domain/user/trainer/controller/TrainerController.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/model/Trainer.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/service/TrainerService.java
---
- 도메인
---
Controller 에서 ID값을 반환하도록 리팩토링 했고 이전에 만들어 놓은 삭제 수정 코드도 추가하였습니다
---
---
---
- 확인해줬으면 하는 부분
---
LoginSuccessHandler 리팩토링
---
---
>  refactor(trainer) : 트레이너 부분 리팩토링 

- src/main/java/org/helloworld/gymmate/security/handler/LoginSuccessHandler.java
- src/main/resources/docs/application.md
---
- 도메인
---
어제 멘토링 받은대로 UriComponentsBuilder를 사용해 Uri 생성하는 방식으로 리팩토링 하였습니다.
그에 맞춰 application.md 파일도 수정하였습니다.
---
---
---
- 확인해줬으면 하는 부분
---
---
---
> refactor(Security) : LoginSuccessHandler 리팩토링

- src/main/java/org/helloworld/gymmate/infra/service/KakaoMapWebClientService.java
- src/main/java/org/helloworld/gymmate/security/handler/LoginSuccessHandler.java
- src/main/java/org/helloworld/gymmate/security/policy/ExpirationPolicy.java
- src/main/resources/docs/application.md
---
- common
---
- client url 분리
- kakao -> kakao-map 으로 수정 (카카오 로그인하고 헷갈릴 것 같아서)
- business(사업자등록증 관련) 추가
- jwt secret 키 숨김
---
---
---
- #50 base로 작성됨 (merge 시 같이 적용됨)
- 자동 줄바꿈 적용됨
- 팀원 전체 DM으로 보낸 application.yml 일괄 갱신 예정
---
---
- [GYMMATE-244](https://dia19.atlassian.net/browse/GYMMATE-244)
---
[GYMMATE-244]: https://dia19.atlassian.net/browse/GYMMATE-244?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> config(common): Refactoring Application Config

- src/main/java/org/helloworld/gymmate/domain/user/trainer/controller/TrainerController.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/dto/TrainerProfileRequest.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/model/Trainer.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/service/TrainerService.java
---
- 도메인
---
트레이너 계정의 한줄 소개, 경력, 전문 분야 입력 구현
---
---
---
- 확인해줬으면 하는 부분
---
---
---
> feat(trainer) : 한줄 소개, 경력, 전문 분야 입력 구현 

- src/main/java/org/helloworld/gymmate/security/filter/CustomAuthenticationFilter.java
- src/main/java/org/helloworld/gymmate/security/handler/LoginSuccessHandler.java
- src/main/java/org/helloworld/gymmate/security/policy/ExpirationPolicy.java
- src/main/java/org/helloworld/gymmate/security/token/JwtManager.java
---
- security
---
#53 : ExpirationPolicy에 있는 토큰 만료 시간을 application,yml에서 받아오도록 변경했는데
ExpirationPolicy가 static이라서 오류 발생  
static을 제거하고 component bean으로 등록함
---
---
---
- 자동 줄바꿈 적용됨
---
---
- [GYMMATE-250](https://dia19.atlassian.net/browse/GYMMATE-250)
---
[GYMMATE-250]: https://dia19.atlassian.net/browse/GYMMATE-250?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(security): ExpirationPolicy Static Error

- src/main/java/org/helloworld/gymmate/domain/user/member/controller/MemberController.java
- src/main/java/org/helloworld/gymmate/domain/user/member/service/MemberService.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/service/TrainerService.java
- src/main/java/org/helloworld/gymmate/security/oauth/entity/Oauth.java
- src/main/java/org/helloworld/gymmate/security/oauth/repository/OauthRepository.java
- src/main/java/org/helloworld/gymmate/security/oauth/service/CustomOAuth2UserService.java
- src/main/java/org/helloworld/gymmate/security/oauth/service/OauthService.java
OAuth 오류 수정
---
- 도메인
---
OAuth에 UserType을 추가하여 회원가입 시에 어떤 타입으로 가입하는지 체크하고
같은 카카오 계정으로 가입해도 트레이너 가입과 유저 가입을 다른 OAuth를 사용하게 만들었습니다.
---
---
---
- 확인해줬으면 하는 부분
---
---
---
> fix(user) : OAuth 오류 수정 

- build.gradle
- src/main/java/org/helloworld/gymmate/common/config/AsyncConfig.java
- src/main/java/org/helloworld/gymmate/common/initializer/SpatialIndexInitializer.java
- src/main/java/org/helloworld/gymmate/common/initializer/SpatialIndexService.java
- src/main/java/org/helloworld/gymmate/common/util/GeometryUtil.java
- src/main/java/org/helloworld/gymmate/domain/gym/gym/controller/GymController.java
- src/main/java/org/helloworld/gymmate/domain/gym/gym/dto/GymCreateRequest.java
- src/main/java/org/helloworld/gymmate/domain/gym/gym/dto/GymUpdateRequest.java
- src/main/java/org/helloworld/gymmate/domain/gym/gym/entity/Gym.java
- src/main/java/org/helloworld/gymmate/domain/gym/gym/entity/GymImage.java
- src/main/java/org/helloworld/gymmate/domain/gym/gym/mapper/GymMapper.java
- src/main/java/org/helloworld/gymmate/domain/gym/gym/repository/GymRepository.java
- src/main/java/org/helloworld/gymmate/domain/gym/gym/service/GymService.java
- src/main/java/org/helloworld/gymmate/domain/pt/pt_product/dto/PtProductResponse.java
- src/main/java/org/helloworld/gymmate/domain/pt/pt_product/mapper/PtProductMapper.java
- src/main/java/org/helloworld/gymmate/infra/domain/gym/SeoulGymWebClientCrawler.java
- src/main/java/org/helloworld/gymmate/infra/service/KakaoMapWebClientService.java
- src/main/resources/application-prod.yml
reafactor(gym) : 공간좌표계 도입
---
- gym
---
- 공간좌표계 추가했습니다.
- 사용법 관련해서는 말씀을 드리는게 좋을것 같습니다.
---
---
---
- `GymService.findNearbyGyms`
---
---
---
> reafactor(gym) : 공간좌표계 도입

- src/main/java/org/helloworld/gymmate/domain/gym/gym/mapper/GymMapper.java
- src/main/java/org/helloworld/gymmate/domain/pt/classtime/controller/ClasstimeController.java
- src/main/java/org/helloworld/gymmate/domain/pt/classtime/service/ClasstimeService.java
---
- 도메인
---
---
---
---
- 확인해줬으면 하는 부분
---
---
---
> refactor(pt) : AuthenticationPrincipal 등록

- src/main/java/org/helloworld/gymmate/common/config/SecurityConfig.java
fix(pt) : Security Config fix
---
- pt
- ptProduct 
---
---
---
---
- 확인해줬으면 하는 부분
---
---
---
> fix(pt) : Security Config fix

- src/main/java/org/helloworld/gymmate/domain/user/member/controller/MemberController.java
- src/main/java/org/helloworld/gymmate/domain/user/member/dto/MemberCheckResponse.java
- src/main/java/org/helloworld/gymmate/domain/user/member/mapper/MemberMapper.java
- src/main/java/org/helloworld/gymmate/domain/user/member/service/MemberService.java
- 유저 타입 체크 로직 (member)
- 컨트롤러, 서비스 코드
- dto, mapper
> feat(member): 유저 타입 체크 로직

- src/main/java/org/helloworld/gymmate/common/config/SecurityConfig.java
- src/main/java/org/helloworld/gymmate/domain/pt/pt_product/controller/PtProductController.java
- src/main/java/org/helloworld/gymmate/domain/pt/pt_product/service/PtProductService.java
feat(도메인): ptProduct TODO 완료
---
- pt
- ptProduct
---
---
---
---
- 확인해줬으면 하는 부분
---
---
---
> refactor(pt) : ptProduct TODO 완료

- src/main/java/org/helloworld/gymmate/domain/user/member/controller/MemberController.java
- src/main/java/org/helloworld/gymmate/domain/user/member/dto/MemberModifyRequest.java
- src/main/java/org/helloworld/gymmate/domain/user/member/entity/Member.java
- src/main/java/org/helloworld/gymmate/domain/user/member/service/MemberService.java
- member
- 컨트롤러, 서비스
- MemberModifyRequest DTO
- member 엔티티 : member 객체와, memberModifyRequest DTO를 받아서 member 객체 수정하는 메소드 추가
> feat(member):member정보 수정 로직

- src/main/java/org/helloworld/gymmate/domain/gym/gymInfo/service/GymService.java
---
- 도메인
gym(facility)
---
제휴 헬스장 수정
---
---
---
- 확인해줬으면 하는 부분
---
편의시설 목록 조회
---
---
> feat(gym) : GymService 편의시설 업데이트 추가

- src/main/java/org/helloworld/gymmate/common/exception/ErrorCode.java
- src/main/java/org/helloworld/gymmate/domain/gym/machine/controller/MachineController.java
- src/main/java/org/helloworld/gymmate/domain/gym/machine/dto/MachineCreateRequest.java
- src/main/java/org/helloworld/gymmate/domain/gym/machine/mapper/MachineMapper.java
- src/main/java/org/helloworld/gymmate/domain/gym/machine/service/MachineService.java
feat(machine) : 등록된 머신 삭제
---
- machine
---
- 등록된 머신 삭제
---
---
---
- 확인해줬으면 하는 부분
---
---
---
> feat(machine) : 등록된 머신 삭제

- src/main/java/org/helloworld/gymmate/common/config/SecurityConfig.java
- src/main/java/org/helloworld/gymmate/domain/gym/facility/dto/FacilityResponse.java
- src/main/java/org/helloworld/gymmate/domain/gym/facility/mapper/FacilityMapper.java
- src/main/java/org/helloworld/gymmate/domain/gym/gymInfo/controller/GymController.java
- src/main/java/org/helloworld/gymmate/domain/gym/gymInfo/service/GymService.java
- src/main/java/org/helloworld/gymmate/domain/gym/machine/controller/MachineController.java
---
- 도메인
gym(facility)
---
- 편의 시설 조회 구현 (Service단에만 구현)
- MachineController 에서 Machine + Facility 조회로 합칠 예정
---
---
- 확인해줬으면 하는 부분
---
---
---
> feat(gym) : 편의 시설 조회 구현

- src/main/java/org/helloworld/gymmate/common/config/SecurityConfig.java
- src/main/java/org/helloworld/gymmate/common/exception/ErrorCode.java
- src/main/java/org/helloworld/gymmate/domain/gym/gymInfo/controller/GymController.java
- src/main/java/org/helloworld/gymmate/domain/gym/machine/controller/MachineController.java
- src/main/java/org/helloworld/gymmate/domain/gym/machine/dto/FacilityAndMachineResponse.java
- src/main/java/org/helloworld/gymmate/domain/gym/machine/dto/MachineResponse.java
- src/main/java/org/helloworld/gymmate/domain/gym/machine/mapper/MachineMapper.java
- src/main/java/org/helloworld/gymmate/domain/gym/machine/repository/MachineRepository.java
- src/main/java/org/helloworld/gymmate/domain/gym/machine/service/MachineService.java
feat(machine) : 기구목록 조회
---
- gym (컨트롤러)
- machine (서비스)
---
- feat : 헬스장 주인이 헬스장 정보 수정할 때, 그 때 보일 수 있는 리스트 (페이지 x)
- feat : 기구 + 편의시설 조회
- refactor : 머신 등록 갯수 제한 (30개)
---
---
---
- 상수 따로 빼야할지 (yml)
---
---
---
> feat(machine) : 기구목록 조회

- src/main/java/org/helloworld/gymmate/domain/gym/gymInfo/service/GymService.java
- src/main/java/org/helloworld/gymmate/domain/gym/machine/service/MachineService.java
chore(gym) : 변수타입 변경
---
- gym
---
- 인자타입 변경
---
---
---
- 확인해줬으면 하는 부분
---
---
---
> chore(gym) : 함수 인자타입 변경

- src/main/java/org/helloworld/gymmate/common/exception/ErrorCode.java
- src/main/java/org/helloworld/gymmate/domain/gym/gymInfo/controller/GymController.java
- src/main/java/org/helloworld/gymmate/domain/gym/gymInfo/service/GymService.java
refactor(gym)
---
- gym
---
- 기존 gymId로 Gym을 직접 조회하던 방식에서 partnerGymId로 PartnerGym을 조회한 후 Gym을 수정하도록 변경
- Gym 수정 후 partnerGymId를 반환하도록 변경
---
---
- 이전에 작업한 `gym/feat/GYMMATE-189`이 main에 병합되지 않아 해당 commit이 함께 보이고 있습니다. 참고 부탁드립니다
---
---
- GYMMATE-90
---
> refactor(gym) : 제휴 헬스장 수정 리팩토링

- src/main/java/org/helloworld/gymmate/domain/gym/machine/controller/MachineController.java
- src/main/java/org/helloworld/gymmate/domain/gym/machine/dto/MachineRequest.java
- src/main/java/org/helloworld/gymmate/domain/gym/machine/entity/Machine.java
- src/main/java/org/helloworld/gymmate/domain/gym/machine/mapper/MachineMapper.java
- src/main/java/org/helloworld/gymmate/domain/gym/machine/service/MachineService.java
feat(machine) : machine 수정
---
- gym
- machine
---
- 기존 create나 request dto가 같아 명칭 변경후 재사용
---
---
---
- 확인해줬으면 하는 부분
---
---
---
> feat(machine) : machine 수정

- docker/gymmate-deploy/docker-compose.deploy.template
- nginx/nginx.conf
---
- deploy
---
- HTTPS 적용을 위해 필요해서 추가
---
---
---
- 병합 부탁드립니다
---
- 인증서 발급
---
- .
---
> chore(deploy): Add Nginx

- src/main/java/org/helloworld/gymmate/domain/gym/gymTicket/entity/GymTicket.java
- src/main/java/org/helloworld/gymmate/domain/gym/gymTicket/enums/GymTicketStatus.java
- src/main/java/org/helloworld/gymmate/domain/gym/gymTicket/mapper/GymTicketMapper.java
- src/main/java/org/helloworld/gymmate/domain/gym/gymTicket/repository/GymTicketRepository.java
- src/main/java/org/helloworld/gymmate/domain/gym/gymTicket/service/GymTicketService.java
- src/main/java/org/helloworld/gymmate/domain/user/member/entity/Member.java
feat(gym) : gymTicket 등록
---
- gym
- gymTicket
---
- gymTicket (product 구매 했을 경우) 구현
---
---
---
- 컨트롤러 Ticket에 만드나요 Product에 만드나요
---
---
---
> feat(gym) : gymTicket 등록

- .github/workflows/deploy.yml
---
- 도메인
---
- EC2에 도커 컴포즈 설치가 안되어있어서 발생함
---
---
---
- 강제 병합
---
- 
---
---
> chore(deploy): Fix EC2 DocerCompose Error

- src/main/java/org/helloworld/gymmate/common/exception/ErrorCode.java
- src/main/java/org/helloworld/gymmate/domain/gym/gymProduct/service/GymProductService.java
- src/main/java/org/helloworld/gymmate/domain/gym/gymTicket/controller/GymTicketController.java
- src/main/java/org/helloworld/gymmate/domain/gym/gymTicket/dto/GymTicketPurchaseResponse.java
- src/main/java/org/helloworld/gymmate/domain/gym/gymTicket/mapper/GymTicketMapper.java
- src/main/java/org/helloworld/gymmate/domain/gym/gymTicket/service/GymTicketService.java
- src/main/java/org/helloworld/gymmate/domain/user/member/entity/Member.java
feat(gym) : ticket 구매
---
- gym
- gymTicket
---
- 프론트단에서 결제페이지 띄울때 필요한 정보제공 컨트롤러 개발 (상의안해봄)
- 실제 Ticket 결제과정 및 엔티티 생성하는 컨트롤러 개발
- checkPurchaseAvailability 안쓸 수도 있음
---
---
---
- 확인해줬으면 하는 부분
---
- 캐시 로그
- 캐시 업데이트는 나중에 캐시 서비스로 분리
---
---
> feat(gym) : ticket 구매

- src/main/java/org/helloworld/gymmate/common/config/SecurityConfig.java
- src/main/java/org/helloworld/gymmate/domain/gym/gyminfo/controller/GymController.java
- src/main/java/org/helloworld/gymmate/domain/gym/gyminfo/dto/response/GymDetailResponse.java
- src/main/java/org/helloworld/gymmate/domain/gym/gyminfo/mapper/GymMapper.java
- src/main/java/org/helloworld/gymmate/domain/gym/gyminfo/service/GymService.java
---
- Gym
---
- 헬스장 정보는 로그인하지 않아도 볼 수있어야해서 SecurityConfig에 추가하였습니다.
---
---
---
- 확인해줬으면 하는 부분
---
멘토님꼐서 말씀하신 사항 리팩토링
---
---
> feat(gym): 헬스장 정보 단일 조회

- src/main/java/org/helloworld/gymmate/domain/gym/gymticket/entity/GymTicket.java
- src/main/java/org/helloworld/gymmate/domain/gym/gymticket/repository/GymTicketRepository.java
- src/main/java/org/helloworld/gymmate/domain/gym/gymticket/service/GymTicketScheduler.java
feat(gym) : 헬스장 티켓 자동 만료 스케쥴러
---
- gym
- gymticket
---
- 매일 자정, 만료일이 이전 날짜이면서 상태가 ACTIVE인 ticket의 상태를 EXPIRED로 변경
---
---
---
- 확인해줬으면 하는 부분
---
---
---
> feat(gym) : 헬스장 티켓 자동 만료 스케쥴러

- src/main/java/org/helloworld/gymmate/domain/gym/gymticket/controller/GymTicketController.java
- src/main/java/org/helloworld/gymmate/domain/gym/gymticket/dto/MemberGymTicketResponse.java
- src/main/java/org/helloworld/gymmate/domain/gym/gymticket/dto/TicketResponse.java
- src/main/java/org/helloworld/gymmate/domain/gym/gymticket/mapper/GymTicketMapper.java
- src/main/java/org/helloworld/gymmate/domain/gym/gymticket/repository/GymTicketRepository.java
- src/main/java/org/helloworld/gymmate/domain/gym/gymticket/service/GymTicketService.java
feat(gym) : ticket 조회 (member)
---
- gym
- gymticket
---
- member 자신의 gymTicket들 조회 (페이지)
---
---
---
- member.getTickets() 대신 쿼리문 작성
- dto 관련 : 멤버가 볼 때에는 partnergymId가 필요할것 같아 추가, 추후 gym owner 입장에서 조회할 때에는 가입한 member 관련 조회가 필요할 것 같아 dto 이름 작성
---
---
---
> feat(gym) : ticket 조회 (member)

- src/main/java/org/helloworld/gymmate/common/exception/ErrorCode.java
- src/main/java/org/helloworld/gymmate/domain/gym/gymproduct/service/GymProductService.java
- src/main/java/org/helloworld/gymmate/domain/gym/partnergym/dto/request/GymRegisterRequest.java
- src/main/java/org/helloworld/gymmate/domain/gym/partnergym/dto/request/GymRequest.java
- src/main/java/org/helloworld/gymmate/domain/gym/partnergym/service/PartnerGymService.java
refactor(gymProduct)
---
- gym
---
- reuqestDto에서 불필요한 message 검증 삭제
- 제휴헬스장 수정 시 반환값 gymId → partnerGymId로 수정
- 파트너짐 id + 이용권 id로 해당 파트너짐 이용권이 맞는지 검증하는 로직 추가
---
---
---
- 확인해줬으면 하는 부분
---
---
- GYMMATE-321
---
> refactor(gymProduct) : 제휴 헬스장 이용권 수정

- src/main/java/org/helloworld/gymmate/domain/gym/gymticket/controller/GymTicketController.java
- src/main/java/org/helloworld/gymmate/domain/gym/gymticket/dto/PartnerGymTicketResponse.java
- src/main/java/org/helloworld/gymmate/domain/gym/gymticket/mapper/GymTicketMapper.java
- src/main/java/org/helloworld/gymmate/domain/gym/gymticket/repository/GymTicketRepository.java
- src/main/java/org/helloworld/gymmate/domain/gym/gymticket/service/GymTicketService.java
- src/main/java/org/helloworld/gymmate/domain/gym/partnergym/service/PartnerGymService.java
feat(gym) : owner ticket 조회
---
- gym
- gymticket
---
- 헬스장 주인입장에서의 티켓 내용 조회 기능
---
---
---
- 확인해줬으면 하는 부분
---
---
---
> feat(gym) : owner ticket 조회

- src/main/java/org/helloworld/gymmate/domain/gym/gyminfo/dto/response/GymListResponse.java
- src/main/java/org/helloworld/gymmate/domain/gym/gyminfo/mapper/GymMapper.java
---
- Gym
---
- 프론트에서 헬스장 목록조회에서도 x,y 좌표가 필요하다고 하셔서 항목을 추가하고 기존 placeUrl -> address로 수정하였습니다
---
---
---
- 확인해줬으면 하는 부분
---
---
---
> refactor(gym) : GymListResponse 항목 추가 및 수정 

- src/main/java/org/helloworld/gymmate/domain/gym/gyminfo/controller/GymController.java
- src/main/java/org/helloworld/gymmate/domain/gym/gyminfo/repository/GymRepository.java
---
- gym
---
- 기존 코드에서는 isPartner값이 true로 고정되어있어 제휴 헬스장과 제휴헬스장이 아닌 헬스장 목록 전체조회가 불가능 했습니다 
- 이를 수정하기위해 isPartner 기본값을 NULL로 수정하고 Repository 쿼리에 isPartner is NULL을 추가하여 전체 목록조회가 가능하도록 수정하였습니다.
---
---
---
- 확인해줬으면 하는 부분
---
트레이너 추가정보 등록시 헬스장 검색 부분 추가
---
---
> refactor(gym) : 헬스장 정보 목록 & 검색 결과 조회 리팩토링

- src/main/java/org/helloworld/gymmate/domain/gym/gyminfo/controller/GymController.java
- src/main/java/org/helloworld/gymmate/domain/gym/gyminfo/dto/response/GymSearchResponse.java
- src/main/java/org/helloworld/gymmate/domain/gym/gyminfo/entity/Gym.java
- src/main/java/org/helloworld/gymmate/domain/gym/gyminfo/mapper/GymMapper.java
- src/main/java/org/helloworld/gymmate/domain/gym/gyminfo/repository/GymRepository.java
- src/main/java/org/helloworld/gymmate/domain/gym/gyminfo/service/GymService.java
---
- gym
---
- 트레이너(직원) 가입시 헬스장 정보 반환 구현
---
---
---
- 확인해줬으면 하는 부분
---
---
---
> feat(gym) : 트레이너(직원) 가입시 헬스장 정보 반환 구현

- src/main/java/org/helloworld/gymmate/domain/gym/gyminfo/entity/Gym.java
- src/main/java/org/helloworld/gymmate/infra/domain/gym/SeoulGymWebClientCrawler.java
refactor(gym) : 더미데이터 삭제
---
- infra
---
- DB 서버에 실었으니 더미데이터 인풋은 삭제하는게 맞다고 생각했습니다.
- 크롤링 관련해서 없는 값들에 대해 null 값을 집어넣는 것으로 수정했는데, 아직 엔티티에 nullable = false 설정이 남아있어 크롤링이 돌아가지 않아 수정하였습니다. 그런데 V1_init_schema 안건드려도 크롤링 된다고 합니다. (왜 되는지 모름)
---
---
---
- 확인해줬으면 하는 부분
---
---
---
> refactor(gym) : 더미데이터 삭제

- src/main/java/org/helloworld/gymmate/domain/gym/gymticket/dto/MemberGymTicketResponse.java
- src/main/java/org/helloworld/gymmate/domain/gym/gymticket/mapper/GymTicketMapper.java
- src/main/java/org/helloworld/gymmate/domain/gym/gymticket/service/GymTicketService.java
- src/main/java/org/helloworld/gymmate/domain/gym/partnergym/dao/PartnerGymNameProjection.java
- src/main/java/org/helloworld/gymmate/domain/gym/partnergym/repository/PartnerGymRepository.java
- src/main/java/org/helloworld/gymmate/domain/gym/partnergym/service/PartnerGymService.java
refactor(gym) : 프론트 필요 항목
---
- gym
- gymTicket
---
- 파트너짐 id 항목은 어차피 내역에서 헬스장으로 이동안할거라 제외
- 대신 짐 이름이 필요하다 하셔서 추가
---
---
---
- 확인해줬으면 하는 부분
---
---
---
> refactor(gym) : 프론트 필요 항목

- src/main/java/org/helloworld/gymmate/domain/user/trainer/controller/TrainerController.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/dto/TrainerModifyRequest.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/entity/Trainer.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/service/TrainerService.java
---
- 도메인
trainer
---
- 트레이너 프로필사진 업데이트 리팩토링
---
---
---
- 확인해줬으면 하는 부분
---
---
---
> refactor(trainer) : 트레이너 프로필사진 업데이트

- src/main/java/org/helloworld/gymmate/common/exception/ErrorCode.java
- src/main/java/org/helloworld/gymmate/domain/pt/reservation/service/ReservationService.java
- src/main/java/org/helloworld/gymmate/domain/pt/student/controller/StudentController.java
- src/main/java/org/helloworld/gymmate/domain/pt/student/dto/StudentDetailResponse.java
- src/main/java/org/helloworld/gymmate/domain/pt/student/mapper/StudentMapper.java
- src/main/java/org/helloworld/gymmate/domain/pt/student/service/StudentService.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/entity/Trainer.java
---
- 도메인
---
---
---
---
- 확인해줬으면 하는 부분
---
---
---
> feat(student) : 단일조회, 생성연결

- src/main/java/org/helloworld/gymmate/domain/pt/reservation/controller/ReservationController.java
- src/main/java/org/helloworld/gymmate/domain/pt/reservation/entity/Reservation.java
- src/main/java/org/helloworld/gymmate/domain/pt/reservation/service/ReservationService.java
- 요청 파라미터 : 수정할 reservationId
- 요청 바디 : 수정할 date, time
- 서비스 : reservation 객체 찾아서, date, time 수정
---
- 포스트맨 테스트 완료
---
---
> feat(reservation): 예약 수정

- src/main/java/org/helloworld/gymmate/common/config/SecurityConfig.java
- src/main/java/org/helloworld/gymmate/common/cookie/CookieManager.java
- src/main/resources/docs/application-deploy.template
반드시 이거 병합 이후 재배포 해야 함
병합 전 배포하면 문제 생김!!!
---
- security
---
- 로그인 쿠키 수정 
이 부분 바꿔야한다고 강사님께서 말씀하시긴 했는데 정확히 왜 바꿔야하는지는 모릅니다
- cors 주소 추가
- 배포 환경 설정 클라이언트 주소 -> vercel
---
---
---
- 개발 환경 (prod)에서 문제없음
---
- 배포 환경 확인
---
---
> fix(security):Modify Cookie & Add Vercel Cors

- src/main/java/org/helloworld/gymmate/domain/gym/enums/GymDummyImage.java
- src/main/java/org/helloworld/gymmate/domain/gym/gyminfo/mapper/GymMapper.java
- src/main/java/org/helloworld/gymmate/domain/gym/gyminfo/repository/GymRepository.java
- src/main/java/org/helloworld/gymmate/infra/controller/CrawlerController.java
- src/main/java/org/helloworld/gymmate/infra/domain/gym/SeoulGymWebClientCrawler.java
feat(gym) : 더미 이미지 등록
---
- infra
- gym
---
- 더미이미지 등록
- 배치저장 할 때 gym에 id가 없어서 발생하는 문제 해결 (gymMachine, gymImage)
- 기존 랜덤 facility 기능도 그냥 한번에 넣었습니다
---
---
---
- 확인해줬으면 하는 부분
---
---
---
> feat(gym) : 더미 이미지 등록 + id 못불러오는점 수정

- src/main/java/org/helloworld/gymmate/domain/pt/classtime/controller/ClasstimeController.java
- src/main/java/org/helloworld/gymmate/domain/pt/ptproduct/controller/PtProductController.java
- src/main/java/org/helloworld/gymmate/domain/pt/reservation/controller/ReservationController.java
- src/main/java/org/helloworld/gymmate/domain/pt/student/controller/StudentController.java
- src/main/java/org/helloworld/gymmate/domain/pt/student/dto/StudentsResponse.java
- src/main/java/org/helloworld/gymmate/domain/pt/student/mapper/StudentMapper.java
docs(pt) : pt related controller swagger update
---
- 도메인
---
- 컨트롤러 스웨거작업
- Student 전체조회 응답에서 id 안주던점 수정
---
---
---
- 확인해줬으면 하는 부분
---
---
---
> docs(pt) : pt related controller swagger update

- src/main/java/org/helloworld/gymmate/domain/pt/ptproduct/controller/PtProductController.java
- src/main/java/org/helloworld/gymmate/domain/pt/ptproduct/dto/TrainersPtProductsResponse.java
- src/main/java/org/helloworld/gymmate/domain/pt/ptproduct/mapper/PtProductMapper.java
- src/main/java/org/helloworld/gymmate/domain/pt/ptproduct/service/PtProductService.java
- ptProduct
---
- 기존 ptProduct 하나만 주던거 여러개 줘야할 필요가 있다고 판단해 작성
---
---
---
- 확인해줬으면 하는 부분
---
---
---
> feat(ptProduct): 프론트 페이지 반영 컨트롤러 추가

- src/main/java/org/helloworld/gymmate/domain/gym/machine/controller/MachineController.java
---
- gym
---
- MachineController Swagger
---
---
---
- 검토 부탁드립니다
---
---
---
> docs(gym): Write Swagger MachineController

- src/main/java/org/helloworld/gymmate/common/exception/ErrorCode.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/award/controller/AwardController.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/award/dto/AwardRequest.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/award/mapper/AwardMapper.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/award/service/AwardMapper.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/award/service/AwardService.java
feat(award) : 등록 컨트롤러
---
- award
---
- 수상이력 등록
---
---
---
- 확인해줬으면 하는 부분
---
---
---
> feat(award) : 등록 컨트롤러

- src/main/java/org/helloworld/gymmate/common/exception/ErrorCode.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/award/controller/AwardController.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/award/service/AwardService.java
feat(award) : award 삭제
---
- awrd
---
- award 삭제
---
---
---
- 확인해줬으면 하는 부분
---
---
---
> feat(award) : award 삭제

- src/main/java/org/helloworld/gymmate/common/config/SecurityConfig.java
- src/main/java/org/helloworld/gymmate/domain/gym/gyminfo/repository/GymImageRepository.java
- src/main/java/org/helloworld/gymmate/domain/user/enums/SocialProviderType.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/repository/TrainerRepository.java
- src/main/java/org/helloworld/gymmate/dummy/controller/DummyDataController.java
- src/main/java/org/helloworld/gymmate/dummy/entity/GymDummyText.java
- src/main/java/org/helloworld/gymmate/dummy/entity/PartnerGymDummyImage.java
- src/main/java/org/helloworld/gymmate/dummy/entity/TrainerDummyImage.java
- src/main/java/org/helloworld/gymmate/dummy/entity/TrainerDummyText.java
- src/main/java/org/helloworld/gymmate/dummy/service/DummyDataService.java
- src/main/resources/db/migration/V1__init_schema.sql
---
- 도메인
dummy
---
-  이미지 같은 경우는 S3에 올린 이미지를 랜덤으로 넣는 식으로 구현했고 여러 String 값(이름, 은행 등등)도 배열로 만들어 랜덤으로 값을 넣도록 
구현했습니다
- 현재 이러면 트레이너수는 총3000명 만들어지고 일반 트레이너2000명이 각 제휴 헬스장에 2명씩 들어가고
제휴 헬스장 사장님 1000명 이렇게 만들어집니다.
-   제휴 헬스장 등록 하면서 추가하는 여러 정보들도 List에 저장 후 랜덤으로 넣도록 했고 24시간 운영헬스장도 요즘 많이보여서 시작 시간이 00:00 이 들어가면 종료시간이 24:00으로 고정되도록 했습니다.
---
---
---
- 확인해줬으면 하는 부분
---
---
---
>   feat(dummy) : Trainer 및 제휴 헬스장 더미 데이터 생성 

- src/main/java/org/helloworld/gymmate/domain/user/trainer/award/controller/AwardController.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/award/dto/AwardResponse.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/award/mapper/AwardMapper.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/award/service/AwardService.java
feat(award) : 트레이너 본인 award 조회
---
- award
---
- 본인 수상이력 조회 (수상이력 수정페이지용)
---
---
---
- 확인해줬으면 하는 부분
---
---
---
> feat(award) : 트레이너 본인 award 조회

- src/main/java/org/helloworld/gymmate/domain/myself/bigthree/service/BigthreeService.java
---
- 도메인
---
---
---
---
- 확인해줬으면 하는 부분
---
---
---
> fix: 순환 참조 문제 해결

- src/main/java/org/helloworld/gymmate/domain/user/trainer/dto/TrainerResponse.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/mapper/TrainerMapper.java
---
- 도메인
---
- 마이페이지 항목 빠진것 추가 (전화번호, 이메일)
---
---
---
- 확인해줬으면 하는 부분
---
---
---
> refactor(trainer) : 마이페이지 항목 빠진것 추가 

- src/main/java/org/helloworld/gymmate/common/config/SecurityConfig.java
---
- security
---
- EC2 서버 cors 허용 추가
---
---
---
- 확인해줬으면 하는 부분
---
- 나의 운동 페이지에 들어가면 엑세스 토큰이 항상 없다고 뜸
(항상 리프레쉬 토큰으로 접근함)
---
---
> fix(security): Add Cors EC2 Server

- src/main/java/org/helloworld/gymmate/infra/domain/trainer/TrainerDummy.java
feat(trainer):classTime 더미데이터 생성
---
- trainer 객체들을 파라미터로 받아서
- 각 trainer마다 월 ~ 금 , 9시~20시의 classTime을 생성해서 리스트로 저장해두고
- classTime테이블에 500개씩 insert문으로 저장
---
---
> feat(trainer):classTime 더미데이터 생성

- src/main/java/org/helloworld/gymmate/domain/pt/reservation/controller/ReservationController.java
- src/main/java/org/helloworld/gymmate/domain/pt/reservation/entity/Reservation.java
- src/main/java/org/helloworld/gymmate/domain/pt/reservation/service/ReservationService.java
refactor(reservation):(hard)delete -> cancel(soft delete)
- 예약 삭제 (hard delete) -> 예약 취소(soft delete): 예약 날짜 추가
- entity 안의 메소드들 수정 
- 수정, 삭제 api가 id만 반환하게 함
---
---
- 확인해줬으면 하는 부분
---
---
---
> refactor(reservation):(hard)delete -> cancel(soft delete)

- src/main/java/org/helloworld/gymmate/domain/gym/gymproduct/dto/GymProductRequest.java
- src/main/java/org/helloworld/gymmate/domain/gym/gymproduct/repository/GymProductRepository.java
- src/main/java/org/helloworld/gymmate/domain/gym/gymproduct/service/GymProductService.java
- gym
---
- gymProduct/dto/request에서 검증 message 삭제
- gymProduct/respository에 사용하지 않는 메서드 삭제
- gymProduct/service에 메서드 설명 주석 추가
---
---
---
- 확인해줬으면 하는 부분
---
---
- GYMMATE-381
---
> docs(gym): Write Swagger gymProduct

- .github/workflows/deploy.yml
- src/main/resources/docs/application.template
---
- pay
---
- application.yml 환경 변수 추가
깃허브 시크릿 키 설정 & deploy에 추가
---
---
---
- application.yml을 꼭 수정해야 합니다
---
- 배포 업데이트
- #170 PR 병합 후 재배포
---
---
> config(pay): Add Pay Key & Url

- src/main/java/org/helloworld/gymmate/domain/gym/gymticket/controller/GymTicketController.java
---
- gym
---
- 
---
---
---
- 확인해줬으면 하는 부분
---
---
---
> docs(gym): Write Swagger GymTicketController

- src/main/java/org/helloworld/gymmate/common/config/RestClientConfig.java
- src/main/java/org/helloworld/gymmate/common/exception/ErrorCode.java
- src/main/java/org/helloworld/gymmate/domain/payment/controller/PaymentController.java
- src/main/java/org/helloworld/gymmate/domain/payment/dto/request/PaymentRequest.java
- src/main/java/org/helloworld/gymmate/domain/payment/dto/response/PaymentResponse.java
- src/main/java/org/helloworld/gymmate/domain/payment/entity/Payment.java
- src/main/java/org/helloworld/gymmate/domain/payment/interceptor/PaymentAuthInterceptor.java
- src/main/java/org/helloworld/gymmate/domain/payment/mapper/PaymentMapper.java
- src/main/java/org/helloworld/gymmate/domain/payment/properties/PaymentProperties.java
- src/main/java/org/helloworld/gymmate/domain/payment/repository/PaymentRepository.java
- src/main/java/org/helloworld/gymmate/domain/payment/service/PaymentService.java
---
- 도메인
payment
---
- 토스페이먼츠 API를 활용해 결제 기능을 구현하였습니다
- 흐름을 간단히 설명드리면 프론트에서 결제창 및 UI를 모두 담당하고 결제 요청을 백엔드에서 받은 후
그 요청을 토스페이먼츠 API에 요청을 보낸 후 결제 승인 성공/실패 응답을 프론트에게 전달해주는게 백엔드의 역할이라고 합니다
- https://docs.tosspayments.com/guides/v2/payment-widget/integration (토스페이먼츠 공식문서) 공식문서가 잘되어있어서  
한번 읽어보시면 좋을 것 같습니다!
---
---
---
- 확인해줬으면 하는 부분
---
---
---
> feat(payment) : 결제 기능 구현

- src/main/java/org/helloworld/gymmate/dummy/controller/DummyDataController.java
- src/main/java/org/helloworld/gymmate/dummy/trainer/PtProductDummy.java
- src/main/java/org/helloworld/gymmate/dummy/trainer/PtProductImageDummy.java
- src/main/java/org/helloworld/gymmate/dummy/trainer/TrainerDummyCreate.java
- src/main/java/org/helloworld/gymmate/infra/controller/CrawlerController.java
---
- dummy
---
- dummy 폴더로 이동시켰습니다
---
---
---
- 작동 안합니다!!! 첫번쨰 실행 api 부터 막혀요
혹시 헬스장이 500개인 상태에서는 실행을 못하는건가요????
헬스장 개수가 적어도 실행 가능하게 해주세요!!!
---
- 첫번째 api 오류 수정
- 두번째, 세번째 테스트 
- RDS에 적용
---
---
> refacotor(dummy): Add Trainer Dummy API & Refactoring

- src/main/java/org/helloworld/gymmate/common/config/SecurityConfig.java
---
- security
---
- @PreAuthroize 동작 되지 않던 문제 수정 (어노테이션 추가)
---
---
---
- 확인해줬으면 하는 부분
---
---
---
> fix(security) : @PreAuthroize 동작 되지 않던 문제 수정 

- src/main/java/org/helloworld/gymmate/domain/user/member/controller/MemberController.java
- src/main/java/org/helloworld/gymmate/domain/user/member/dto/MemberRequest.java
- src/main/java/org/helloworld/gymmate/domain/user/member/entity/Member.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/controller/TrainerController.java
---
---
---
---
---
---
---
---
> refactor(member&trainer):preauthorize, xyField dto제거

- src/main/java/org/helloworld/gymmate/common/config/SecurityConfig.java
- src/main/java/org/helloworld/gymmate/domain/gym/gymreview/controller/GymReviewController.java
chore(security) : 시큐리티 설정 추가, 엔드포인트 수정
---
- 도메인
---
---
---
---
- 확인해줬으면 하는 부분
---
---
---
> chore(security) : 시큐리티 설정 추가, 엔드포인트 수정

- src/main/java/org/helloworld/gymmate/dummy/service/DummyDataService.java
---
- dummy
---
- 
---
---
---
- 
---
---
---
> fix(dummy): 더미 생성기 헬스장 개수 변수로 변경

- src/main/java/org/helloworld/gymmate/domain/pt/reservation/controller/ReservationController.java
- src/main/java/org/helloworld/gymmate/domain/pt/reservation/dto/ReservationTrainerResponse.java
- src/main/java/org/helloworld/gymmate/domain/pt/reservation/mapper/ReservationMapper.java
- src/main/java/org/helloworld/gymmate/domain/pt/reservation/service/ReservationService.java
- src/main/java/org/helloworld/gymmate/domain/pt/student/repository/StudentRepository.java
- src/main/java/org/helloworld/gymmate/domain/pt/student/service/StudentService.java
refactor(reservation) : PT 예약조회 리팩토링
---
- reservation
---
- 예약 관련해서 리팩토링했습니다.
---
---
---
- 확인해줬으면 하는 부분
---
---
---
> refactor(reservation) : PT 예약조회 리팩토링

- src/main/java/org/helloworld/gymmate/dummy/trainer/PtProductDummy.java
- src/main/java/org/helloworld/gymmate/dummy/trainer/TrainerDummyCreate.java
refactor(dummy):trainer 한명당 ptProduct 2개, classTime 더미 추가
---
- 도메인
---
---
---
---
- 확인해줬으면 하는 부분
---
---
---
> refactor(dummy):trainer 한명당 ptProduct 2개, classTime 더미 추가

- src/main/java/org/helloworld/gymmate/common/config/SecurityConfig.java
fix(security) : 시큐리티 설정변경
---
- security
---
---
---
---
- 확인해줬으면 하는 부분
---
---
---
> fix(security) : 시큐리티 설정변경

- src/main/java/org/helloworld/gymmate/domain/gym/gyminfo/dto/response/GymSearchResponse.java
- src/main/java/org/helloworld/gymmate/domain/gym/gyminfo/mapper/GymMapper.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/dto/TrainerRegisterRequest.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/service/TrainerService.java
refactor(gym,trainer) : dto 변경
---
- 도메인
---
- 프론트랑 같이 병합되야함
---
---
---
- 확인해줬으면 하는 부분
---
---
---
> refactor(gym,trainer) : dto 변경 GymId 추가

- src/main/java/org/helloworld/gymmate/common/exception/ErrorCode.java
- src/main/java/org/helloworld/gymmate/common/exception/GlobalExceptionHandler.java
- src/main/java/org/helloworld/gymmate/domain/gym/partnergym/service/PartnerGymService.java
- gym
---
- 등록/수정 시 발생 가능한 제약조건 위반(DB 유니크, FK 등)을 GlobalExceptionHandler에서 공통 처리
- 제약조건 위반은 CONSTRAINT_VIOLATION으로 응답
- 기존 서비스 레이어에 작성한  try-catch 제거 
---
---
---
- 확인해줬으면 하는 부분
---
---
- GYMMATE-421
---
> refactor(gym): 제휴헬스장 등록 시 ErroCode 추가

- src/main/resources/docs/VX__insert_facility_if_missing.templete
---
- gym
---
- 더미데이터 삽입 시 편의시설이 모두 생기지 않고 비어있는 이슈 존재
-> flyway로 맞춰주도록 함
---
---
---
- 필요 시 꺼내서 사용하기 위해 docs에 넣어두었습니다
---
---
---
> docs(gym): Add FlyWay Docs - Edit Null Facility

- src/main/java/org/helloworld/gymmate/common/exception/ErrorCode.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/trainerreview/controller/TrainerReviewController.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/trainerreview/dto/request/TrainerReviewModifyRequest.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/trainerreview/entity/TrainerReview.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/trainerreview/service/TrainerReviewService.java
---
- 도메인
---
- 트레이너 리뷰 수정 구현
---
---
---
- 확인해줬으면 하는 부분
---
---
---
> feat(trainerreview) : 트레이너 리뷰 수정 구현

- src/main/java/org/helloworld/gymmate/common/config/SecurityConfig.java
- src/main/java/org/helloworld/gymmate/common/config/WebConfig.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/controller/TrainerController.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/trainerreview/controller/TrainerReviewController.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/trainerreview/dto/response/TrainerReviewResponse.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/trainerreview/mapper/TrainerReviewMapper.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/trainerreview/repository/TrainerReviewRepository.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/trainerreview/service/TrainerReviewService.java
---
- trainerreview
---
- trainerId를 Pathvariable로 받아오면 해당 트레이너의 모든 리뷰와 그 리뷰에 해당하는 이미지들을 가져오도록 하였습니다
---
---
---
- API 위치를 TrainerController에 위치 해놓았는데 바꿔야 할 것 같으면 말씀해주시면 수정하겠습니다!
---
---
---
> config(security), feat(trainerreview) : cors 에러 수정 & 트레이너 리뷰 조회

- src/main/java/org/helloworld/gymmate/domain/gym/machine/controller/MachineController.java
---
- 도메인
---
---
---
---
- 확인해줬으면 하는 부분
---
---
---
> fix(gym) : swagger error

- src/main/java/org/helloworld/gymmate/domain/pt/classtime/controller/ClasstimeController.java
- src/main/java/org/helloworld/gymmate/domain/pt/classtime/service/ClasstimeService.java
feat(classtime) : 멤버의 트레이너 수업시간조회
---
- 도메인pt - classtime
---
- 예약 신청할 때, 일단 전체 수업시간이 보여야 신청이 가능하기 때문에 필요하다 하셨습니다. 
- 기존 코드, dto 재사용
---
---
---
- 확인해줬으면 하는 부분
---
---
---
> feat(classtime) : 멤버의 트레이너 수업시간조회

- src/main/java/org/helloworld/gymmate/domain/gym/gymreview/controller/GymReviewController.java
- src/main/java/org/helloworld/gymmate/domain/gym/gymreview/dto/GymReviewRequest.java
- src/main/java/org/helloworld/gymmate/domain/gym/gymreview/event/GymReviewDeleteEvent.java
- src/main/java/org/helloworld/gymmate/domain/gym/gymreview/event/GymReviewDeleteEventListener.java
- src/main/java/org/helloworld/gymmate/domain/gym/gymreview/service/GymReviewService.java
feat(gymreview) : 헬스장 리뷰 삭제
---
- gymReview
---
- 삭제 구현
---
---
---
- 수정에서 구현한 메소드 그대로 호출하고있어서 수정 병합후 병합해야합니다
---
---
---
> feat(gymreview) : 헬스장 리뷰 삭제

- src/main/java/org/helloworld/gymmate/domain/gym/gyminfo/controller/GymController.java
- src/main/java/org/helloworld/gymmate/domain/gym/gyminfo/repository/GymRepository.java
- src/main/java/org/helloworld/gymmate/domain/gym/gyminfo/service/GymService.java
- src/main/java/org/helloworld/gymmate/domain/gym/partnergym/repository/PartnerGymRepository.java
- src/main/java/org/helloworld/gymmate/domain/gym/partnergym/service/PartnerGymService.java
feat(gym) : 제휴 헬스장 등록 주인 없는 헬스장만 조회되는 엔드포인트 추가
---
- gym
---
- 파트너짐 조회해서 존재하는 gymId를 제외한 다른 헬스장 조회
- 제휴헬스장은 1개만 등록 가능하도록 수정
---
---
---
- 확인해줬으면 하는 부분
---
---
---
> feat(gym) : 제휴 헬스장 등록 주인 없는 헬스장만 조회되는 엔드포인트 추가

- src/main/java/org/helloworld/gymmate/domain/pt/ptproduct/entity/PtProduct.java
- src/main/java/org/helloworld/gymmate/domain/pt/ptproduct/service/PtProductService.java
- src/main/java/org/helloworld/gymmate/domain/pt/student/repository/StudentRepository.java
- src/main/java/org/helloworld/gymmate/domain/pt/student/service/StudentService.java
refacor(ptproduct) : pt상품명 수정 안되던점 수정
---
- ptProduct
---
- ptProduct 수정에서 ptProductName 수정 안되던점 수정
- reservation 할 때, student가 자동으로 생성되는데 중복으로 생성되지 않게 수정 (fix 빨리 해야됨)
-  -> 이거 fix안되면 예약 할때마다 중복 수강생이 생겨서 기능에 문제 생깁니다
---
---
---
- 확인해줬으면 하는 부분
---
---
---
> refacor(ptproduct) : pt상품명 수정 안되던점 수정

- src/main/java/org/helloworld/gymmate/common/config/SecurityConfig.java
- src/main/java/org/helloworld/gymmate/domain/gym/gyminfo/controller/GymController.java
- src/main/java/org/helloworld/gymmate/domain/gym/gymreview/dto/GymReviewImageResponse.java
- src/main/java/org/helloworld/gymmate/domain/gym/gymreview/dto/GymReviewResponse.java
- src/main/java/org/helloworld/gymmate/domain/gym/gymreview/mapper/GymReviewMapper.java
- src/main/java/org/helloworld/gymmate/domain/gym/gymreview/repository/GymReviewRepository.java
- src/main/java/org/helloworld/gymmate/domain/gym/gymreview/service/GymReviewService.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/controller/TrainerController.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/trainerreview/dto/response/TrainerReviewResponse.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/trainerreview/mapper/TrainerReviewMapper.java
---
- gymreview
---
- 헬스장 리뷰 조회 구현 (생성날짜, 수정날짜 포함 수정날짜는 없을시 null로 전달)
---
---
---
- 확인해줬으면 하는 부분
---
---
---
> feat(gymreview): 헬스장 리뷰 조회 구현 

- src/main/java/org/helloworld/gymmate/domain/gym/gyminfo/controller/GymController.java
- src/main/java/org/helloworld/gymmate/domain/gym/gyminfo/repository/GymRepository.java
- src/main/java/org/helloworld/gymmate/domain/gym/gyminfo/service/GymService.java
---
- gym
---
- SearchOption이 None일때 Gym + District 포함한 결과 모두 검색 되도록 수정
---
---
---
- 확인해줬으면 하는 부분
---
---
---
> refactor(gym) : 전체 조회 검색 수정/GYMMATE-446

- src/main/java/org/helloworld/gymmate/domain/user/enums/SocialProviderType.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/trainerreview/dto/response/TrainerReviewResponse.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/trainerreview/mapper/TrainerReviewMapper.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/trainerreview/service/TrainerReviewService.java
---
- 도메인
---
---
---
---
- 확인해줬으면 하는 부분
---
---
---
> refactor(trainer_review) : refactor 트레이너 리뷰 리팩터링

- src/main/java/org/helloworld/gymmate/domain/pt/reservation/service/ReservationService.java
---
- 도메인
---
---
---
---
- 확인해줬으면 하는 부분
---
---
---
> refactor(reservation) : 돈 차감

- src/main/java/org/helloworld/gymmate/domain/gym/gymreview/dto/GymReviewResponse.java
- src/main/java/org/helloworld/gymmate/domain/gym/gymreview/mapper/GymReviewMapper.java
- src/main/java/org/helloworld/gymmate/domain/gym/gymreview/service/GymReviewService.java
- src/main/java/org/helloworld/gymmate/domain/pt/reservation/service/ReservationService.java
- src/main/resources/docs/insert_gym_review.template
- src/main/resources/docs/insert_gymmate_member_and_oauth.template
---
- gymreview, member
---
- 멤버 & 헬스장 리뷰 더미데이터 생성 쿼리
---
---
---
- 확인해줬으면 하는 부분
---
---
---
> feat(gym, member) : 멤버 & 헬스장 리뷰 더미데이터 생성 쿼리

- src/main/java/org/helloworld/gymmate/domain/gym/gymreview/service/GymReviewService.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/trainerreview/service/TrainerReviewService.java
---
- 도메인
---
---
---
---
- 확인해줬으면 하는 부분
---
---
---
> refactor(review) : 정렬 DESC

- src/main/java/org/helloworld/gymmate/domain/pt/reservation/service/ReservationService.java
---
- reservation
---
- 이전에는 회원 보유 금액이 PT 금액보다 적어도 예약이 가능 -> 보유 금액이 적을 경우 에러 뜨도록 수정
---
---
---
- 확인해줬으면 하는 부분
---
---
---
> refactor(reservation) : 예약시 회원 보유 금액과 PT 금액 비교 추가 

- src/main/resources/docs/application-deploy.template
---
- 도메인
---
---
---
---
- 확인해줬으면 하는 부분
---
---
---
> fix(deploy): 서버 시간대 변경

- src/main/java/org/helloworld/gymmate/domain/pt/reservation/repository/ReservationRepository.java
---
- reservation
---
- 타임존을 Asia/Seoul로 변환하도록 수정
---
---
---
- 확인해줬으면 하는 부분
---
---
---
> fix(reservation) : 쿼리문 수정 

- src/main/java/org/helloworld/gymmate/domain/gym/gyminfo/entity/Gym.java
- src/main/java/org/helloworld/gymmate/domain/gym/gymreview/event/GymScoreEventListener.java
- src/main/java/org/helloworld/gymmate/domain/gym/gymreview/event/GymScoreUpdateEvent.java
- src/main/java/org/helloworld/gymmate/domain/gym/gymreview/repository/GymReviewRepository.java
- src/main/java/org/helloworld/gymmate/domain/gym/gymreview/service/GymReviewService.java
- src/main/java/org/helloworld/gymmate/domain/pt/ptproduct/dto/TrainersPtProductsResponse.java
- src/main/java/org/helloworld/gymmate/domain/pt/ptproduct/mapper/PtProductMapper.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/entity/Trainer.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/trainerreview/event/TrainerScoreEventListener.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/trainerreview/event/TrainerScoreUpdateEvent.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/trainerreview/repository/TrainerReviewRepository.java
- src/main/java/org/helloworld/gymmate/domain/user/trainer/trainerreview/service/TrainerReviewService.java
---
- 도메인
---
- 트레이너 리뷰 평점반영
- 헬스장 리뷰 평점반영
- 헬스장 리뷰 수정 FIX
- pt Product 상세에서 Gym 정보에 gymId 전달
---
---
---
- 확인해줬으면 하는 부분
---
---
---
> refactor(trainer) : trainer score 리뷰 반영

- src/main/java/org/helloworld/gymmate/domain/gym/gyminfo/repository/GymRepository.java
---
- 도메인
---
---
---
---
- 확인해줬으면 하는 부분
---
---
---
> fix(gym): FindAll Query Fix
